/* ============================================================
   Takatak Zoo — content
   Names are in all three languages; the fact sheets are English.

   Land animal fields
     id       unique key, also the stop order on the jungle path
     models   { m: father, f: mother, b: baby }  → models/animals/<key>.glb
              b:"tadpole" is built in code (no model exists)
     h        height of the father in metres, as shown in the zoo
              (small animals are enlarged so a child can see them)
     len      normalise by body length instead of height (long, flat animals)
     fs, bs   mother / baby size relative to the father
     tint     { f, b } colour multiplied onto that model (0xRRGGBB)
     yaw      extra turn in radians for models that do not face +Z
     n        babies shown in the family view
     eggs     eggs shown in the nest (egg layers only)
     roles    English names for father / mother / baby / babies
     hop      babies (and adult) bounce instead of walk
   ============================================================ */

export const LANGS = {
  en: { label: "English", voice: "en-IN" },
  mr: { label: "मराठी", voice: "mr-IN", fallback: "hi-IN" },
  hi: { label: "हिंदी", voice: "hi-IN" },
};

export const UI = {
  title:      { en: "Takatak Zoo", mr: "टकाटक प्राणीसंग्रहालय", hi: "टकाटक चिड़ियाघर" },
  enter:      { en: "Enter the jungle", mr: "जंगलात चला", hi: "जंगल में चलो" },
  loading:    { en: "Waking up the animals…", mr: "प्राणी उठत आहेत…", hi: "जानवर जाग रहे हैं…" },
  family:     { en: "family", mr: "कुटुंब", hi: "परिवार" },
  father:     { en: "Father", mr: "बाबा", hi: "पिता" },
  mother:     { en: "Mother", mr: "आई", hi: "माँ" },
  baby:       { en: "Baby", mr: "बाळ", hi: "बच्चा" },
  babies:     { en: "Babies", mr: "पिल्ले", hi: "बच्चे" },
  eggs:       { en: "Eggs", mr: "अंडी", hi: "अंडे" },
  pond:       { en: "Fish Pond", mr: "माशांचे तळे", hi: "मछली तालाब" },
  tapPond:    { en: "Tap the water to meet the fish!", mr: "मासे पाहायला पाण्यावर टॅप करा!", hi: "मछलियाँ देखने के लिए पानी पर टैप करो!" },
  edible:     { en: "Fish we eat", mr: "खाण्याचे मासे", hi: "खाने वाली मछलियाँ" },
  inedible:   { en: "Fish we don’t eat", mr: "न खाण्याचे मासे", hi: "न खाने वाली मछलियाँ" },
  back:       { en: "Back", mr: "मागे", hi: "वापस" },
  toJungle:   { en: "Back to the jungle", mr: "जंगलात परत", hi: "जंगल में वापस" },
  hint:       { en: "Tap an animal · drag to look around", mr: "प्राण्यावर टॅप करा · बघायला ओढा", hi: "जानवर पर टैप करो · देखने के लिए खींचो" },
  spin:       { en: "Drag to spin the family all the way round", mr: "कुटुंब फिरवायला ओढा", hi: "परिवार घुमाने के लिए खींचो" },
};

export const ANIMALS = [
  {
    id: "bear", emoji: "🐻", photo: "pics/bear.webp",
    name: { en: "Bear", mr: "अस्वल", hi: "भालू" },
    models: { m: "bear", f: "bear", b: "bear-cub" }, h: 1.5, fs: 0.85, bs: 0.34, n: 2,
    roles: { m: "Boar", f: "Sow", b: "Cub", bs: "Cubs" },
    info: {
      kinds: ["Sloth bear", "Asiatic black bear", "Sun bear", "Brown bear", "Polar bear", "American black bear", "Spectacled bear", "Giant panda"],
      home: "Forests, hills and mountains. India has sloth bears, Asiatic black bears and sun bears.",
      food: "Almost anything — fruit, honey, termites, roots, fish and small animals.",
      life: "About 20–30 years.",
      babies: "Mother bear has 1 to 4 cubs, most often 2. They are born in a warm den, tiny and blind, and stay with her for about 2 years.",
      fact: "A sloth bear can close its nose and suck up termites like a vacuum cleaner!",
    },
  },
  {
    id: "tiger", emoji: "🐯", photo: "pics/tiger.webp",
    name: { en: "Tiger", mr: "वाघ", hi: "बाघ" },
    models: { m: "tiger", f: "tiger", b: "tiger" }, h: 1.1, fs: 0.86, bs: 0.38, n: 3,
    roles: { m: "Tiger", f: "Tigress", b: "Cub", bs: "Cubs" },
    info: {
      kinds: ["Bengal tiger", "Siberian (Amur) tiger", "Sumatran tiger", "Indochinese tiger", "Malayan tiger", "South China tiger"],
      home: "Forests and grasslands of Asia. India has more wild tigers than any other country.",
      food: "Deer, wild boar and buffalo. Tigers hunt alone, mostly at night.",
      life: "About 10–15 years in the wild.",
      babies: "A tigress has 2 to 4 cubs after about 3½ months. The cubs stay with her for about 2 years, learning to hunt.",
      fact: "The tiger is India’s national animal, and no two tigers have the same stripes.",
    },
  },
  {
    id: "lion", emoji: "🦁", photo: "pics/lion.webp",
    name: { en: "Lion", mr: "सिंह", hi: "शेर" },
    models: { m: "lion", f: "lioness", b: "lioness" }, h: 1.2, fs: 0.95, bs: 0.36, n: 3,
    tint: { f: 0xf2d29b, b: 0xf5dcaa },
    roles: { m: "Lion", f: "Lioness", b: "Cub", bs: "Cubs" },
    info: {
      kinds: ["Asiatic lion", "African lion"],
      home: "Asiatic lions live only in the Gir forest of Gujarat. African lions live on the grassy savanna.",
      food: "Deer, antelope, zebra and buffalo. The lionesses do most of the hunting, together as a team.",
      life: "About 10–14 years in the wild.",
      babies: "A lioness has 1 to 4 cubs after about 3½ months. Lions live in a family group called a pride.",
      fact: "Only the father lion has a big mane, and his roar can be heard 8 km away.",
    },
  },
  {
    id: "elephant", emoji: "🐘", photo: "pics/elephant.webp",
    name: { en: "Elephant", mr: "हत्ती", hi: "हाथी" },
    models: { m: "elephant", f: "elephant", b: "elephant" }, h: 3.0, fs: 0.84, bs: 0.36, n: 1,
    roles: { m: "Bull", f: "Cow", b: "Calf", bs: "Calf" },
    info: {
      kinds: ["Asian elephant", "African savanna elephant", "African forest elephant"],
      home: "Forests and grasslands of India, South-East Asia and Africa.",
      food: "Grass, leaves, bark, fruit and bamboo — up to 150 kg of food every day!",
      life: "About 60–70 years.",
      babies: "Mother elephant has 1 calf. She carries it for 22 months — the longest of any land animal. The calf weighs about 100 kg when it is born.",
      fact: "An elephant’s trunk has around 40,000 muscles. It uses it like a nose, a hand and a hose.",
    },
  },
  {
    id: "giraffe", emoji: "🦒",
    name: { en: "Giraffe", mr: "जिराफ", hi: "जिराफ़" },
    models: { m: "giraffe", f: "giraffe", b: "giraffe" }, h: 5.0, fs: 0.86, bs: 0.36, n: 1,
    roles: { m: "Bull", f: "Cow", b: "Calf", bs: "Calf" },
    info: {
      kinds: ["Masai giraffe", "Reticulated giraffe", "Northern giraffe", "Southern giraffe"],
      home: "The dry savanna of Africa.",
      food: "Leaves from tall acacia trees, pulled off with a long purple tongue.",
      life: "About 25 years.",
      babies: "Mother giraffe has 1 calf after about 15 months. The baby drops about 2 metres to the ground when it is born, and stands up within an hour!",
      fact: "The giraffe is the tallest animal on Earth — but its neck has just 7 bones, the same as ours.",
    },
  },
  {
    id: "zebra", emoji: "🦓", photo: "pics/zebra.webp",
    name: { en: "Zebra", mr: "झेब्रा", hi: "ज़ेबरा" },
    models: { m: "zebra", f: "zebra", b: "zebra" }, h: 1.5, fs: 0.92, bs: 0.5, n: 1,
    roles: { m: "Stallion", f: "Mare", b: "Foal", bs: "Foal" },
    info: {
      kinds: ["Plains zebra", "Grévy’s zebra", "Mountain zebra"],
      home: "Grasslands and savanna of Africa.",
      food: "Mostly grass.",
      life: "About 20–25 years.",
      babies: "A mare has 1 foal after about a year. The foal can stand within minutes and run within an hour.",
      fact: "Every zebra’s stripes are different, like our fingerprints.",
    },
  },
  {
    id: "deer", emoji: "🦌", photo: "pics/deer.webp",
    name: { en: "Deer", mr: "हरीण", hi: "हिरण" },
    models: { m: "stag", f: "doe", b: "doe" }, h: 1.7, fs: 0.8, bs: 0.45, n: 1,
    roles: { m: "Stag", f: "Doe", b: "Fawn", bs: "Fawn" },
    info: {
      kinds: ["Chital (spotted deer)", "Sambar", "Barasingha", "Barking deer", "Red deer", "Reindeer", "Moose"],
      home: "Forests and grasslands. The chital is the deer you see most in Indian forests.",
      food: "Grass, leaves, fruit and flowers.",
      life: "About 15–20 years.",
      babies: "A doe usually has 1 fawn. It hides quietly in the grass while its mother eats nearby.",
      fact: "Only the father has antlers. They fall off every year and grow back even bigger.",
    },
  },
  {
    id: "monkey", emoji: "🐒",
    name: { en: "Monkey", mr: "माकड", hi: "बंदर" },
    models: { m: "monkey", f: "monkey", b: "monkey" }, h: 0.9, fs: 0.85, bs: 0.45, n: 1,
    roles: { m: "Male", f: "Female", b: "Baby", bs: "Baby" },
    info: {
      kinds: ["Rhesus macaque", "Bonnet macaque", "Hanuman langur", "Lion-tailed macaque", "Capuchin", "Spider monkey"],
      home: "Forests, hills, temples and even cities.",
      food: "Fruit, leaves, seeds, insects — and snacks stolen from people!",
      life: "About 20–25 years.",
      babies: "A mother monkey has 1 baby after about 5½ months. It holds on tight to her tummy as she climbs.",
      fact: "Monkeys groom each other to stay clean and to show they are friends.",
    },
  },
  {
    id: "gorilla", emoji: "🦍",
    name: { en: "Gorilla", mr: "गोरिला", hi: "गोरिल्ला" },
    models: { m: "gorilla", f: "gorilla", b: "gorilla" }, h: 1.7, fs: 0.8, bs: 0.36, n: 1,
    roles: { m: "Silverback", f: "Female", b: "Infant", bs: "Infant" },
    info: {
      kinds: ["Western gorilla", "Eastern gorilla (incl. mountain gorilla)"],
      home: "Rainforests of central Africa.",
      food: "Leaves, stems, fruit and bamboo shoots.",
      life: "About 35–40 years.",
      babies: "A mother gorilla has 1 baby after about 8½ months and carries it on her back.",
      fact: "The gorilla is the biggest ape. Grown-up fathers get silver hair on their backs.",
    },
  },
  {
    id: "chimpanzee", emoji: "🐵",
    name: { en: "Chimpanzee", mr: "चिंपांझी", hi: "चिंपैंजी" },
    models: { m: "chimpanzee", f: "chimpanzee", b: "chimpanzee" }, h: 1.3, fs: 0.88, bs: 0.4, n: 1,
    roles: { m: "Male", f: "Female", b: "Baby", bs: "Baby" },
    info: {
      kinds: ["Common chimpanzee", "Bonobo"],
      home: "Forests of central and west Africa.",
      food: "Fruit, leaves, nuts, insects and sometimes meat.",
      life: "About 40–50 years.",
      babies: "A mother chimp has 1 baby after about 8 months, and it stays close to her for 5 years.",
      fact: "Chimps use sticks as tools to fish termites out of their mounds.",
    },
  },
  {
    id: "panda", emoji: "🐼",
    name: { en: "Panda", mr: "पांडा", hi: "पांडा" },
    models: { m: "panda", f: "panda", b: "panda" }, h: 1.0, fs: 0.9, bs: 0.35, n: 1,
    roles: { m: "Boar", f: "Sow", b: "Cub", bs: "Cub" },
    info: {
      kinds: ["Giant panda (a kind of bear)", "Red panda (a different animal, not a bear)"],
      home: "Cool, misty bamboo forests in the mountains of China.",
      food: "Bamboo, bamboo and more bamboo — eating for 12 hours a day!",
      life: "About 20 years.",
      babies: "Mother panda usually has 1 cub. It is born pink, blind and about as heavy as an apple — 900 times smaller than its mother.",
      fact: "Pandas have a special thumb-like bone on their wrist to hold bamboo.",
    },
  },
  {
    id: "hippo", emoji: "🦛",
    name: { en: "Hippopotamus", mr: "पाणघोडा", hi: "दरियाई घोड़ा" },
    models: { m: "hippo", f: "hippo", b: "hippo" }, h: 1.5, fs: 0.9, bs: 0.38, n: 1,
    roles: { m: "Bull", f: "Cow", b: "Calf", bs: "Calf" },
    info: {
      kinds: ["Common hippo", "Pygmy hippo"],
      home: "Rivers and lakes in Africa.",
      food: "Grass — hippos come out of the water at night to graze.",
      life: "About 40–50 years.",
      babies: "Mother hippo has 1 calf after about 8 months. It can be born under water and swims up for its first breath.",
      fact: "Hippos make a red, oily sweat that works like sunscreen.",
    },
  },
  {
    id: "rhino", emoji: "🦏",
    name: { en: "Rhinoceros", mr: "गेंडा", hi: "गैंडा" },
    models: { m: "rhino", f: "rhino", b: "rhino" }, h: 1.7, fs: 0.9, bs: 0.38, n: 1,
    roles: { m: "Bull", f: "Cow", b: "Calf", bs: "Calf" },
    info: {
      kinds: ["Indian (one-horned) rhino", "White rhino", "Black rhino", "Javan rhino", "Sumatran rhino"],
      home: "Grasslands and swamps. Kaziranga in Assam is home to most one-horned rhinos.",
      food: "Grass, leaves, fruit and water plants.",
      life: "About 35–45 years.",
      babies: "Mother rhino has 1 calf after about 16 months. The calf can walk soon after it is born.",
      fact: "A rhino’s horn is made of keratin — the same stuff as your nails and hair.",
    },
  },
  {
    id: "crocodile", emoji: "🐊",
    name: { en: "Crocodile", mr: "मगर", hi: "मगरमच्छ" },
    models: { m: "crocodile", f: "crocodile", b: "crocodile" }, len: 3.6, fs: 0.8, bs: 0.18, n: 3, eggs: 12,
    roles: { m: "Male", f: "Female", b: "Hatchling", bs: "Hatchlings" },
    info: {
      kinds: ["Mugger (marsh) crocodile", "Saltwater crocodile", "Gharial", "Nile crocodile"],
      home: "Rivers, lakes and marshes. India has muggers, saltwater crocodiles and gharials.",
      food: "Fish, birds and animals that come to drink.",
      life: "About 60–70 years.",
      babies: "Mother crocodile lays 20 to 60 eggs in a nest and guards them. When the babies squeak, she digs them out and carries them gently in her mouth to the water.",
      fact: "How warm the nest is decides whether the babies are boys or girls.",
    },
  },
  {
    id: "cheetah", emoji: "🐆",
    name: { en: "Cheetah", mr: "चित्ता", hi: "चीता" },
    models: { m: "cheetah", f: "cheetah", b: "cheetah" }, h: 0.95, fs: 0.92, bs: 0.4, n: 4,
    roles: { m: "Male", f: "Female", b: "Cub", bs: "Cubs" },
    info: {
      kinds: ["African cheetah", "Asiatic cheetah"],
      home: "Open grasslands. Cheetahs came back to India in 2022, at Kuno National Park.",
      food: "Gazelles, antelope and hares.",
      life: "About 10–12 years.",
      babies: "A mother cheetah has 3 to 5 cubs after about 3 months. The cubs have fluffy grey fur on their backs.",
      fact: "The cheetah is the fastest land animal — up to about 100 km per hour!",
    },
  },
  {
    id: "camel", emoji: "🐪", photo: "pics/camel.webp",
    name: { en: "Camel", mr: "उंट", hi: "ऊँट" },
    models: { m: "camel", f: "camel", b: "camel" }, h: 2.2, fs: 0.92, bs: 0.45, n: 1, yaw: -Math.PI / 2,
    roles: { m: "Bull", f: "Cow", b: "Calf", bs: "Calf" },
    info: {
      kinds: ["Dromedary (one hump) — Rajasthan", "Bactrian (two humps) — Ladakh"],
      home: "Hot deserts, and cold deserts too.",
      food: "Thorny plants, dry grass and leaves.",
      life: "About 40–50 years.",
      babies: "Mother camel has 1 calf after about 13 months. It can walk within a few hours.",
      fact: "The hump stores fat, not water. A thirsty camel can drink 100 litres in 15 minutes.",
    },
  },
  {
    id: "kangaroo", emoji: "🦘",
    name: { en: "Kangaroo", mr: "कांगारू", hi: "कंगारू" },
    models: { m: "kangaroo", f: "kangaroo", b: "kangaroo" }, h: 1.6, fs: 0.8, bs: 0.3, n: 1, hop: true,
    roles: { m: "Boomer", f: "Flyer", b: "Joey", bs: "Joey" },
    info: {
      kinds: ["Red kangaroo", "Eastern grey kangaroo", "Western grey kangaroo", "Antilopine kangaroo"],
      home: "Grasslands and bush of Australia.",
      food: "Grass and leaves.",
      life: "About 10–20 years.",
      babies: "The joey is born after about a month, as small as a jelly bean. It crawls into mum’s pouch and stays there for about 8 months.",
      fact: "Kangaroos cannot walk backwards — and they hop up to 9 metres in one jump.",
    },
  },
  {
    id: "koala", emoji: "🐨",
    name: { en: "Koala", mr: "कोआला", hi: "कोआला" },
    models: { m: "koala", f: "koala", b: "koala" }, h: 0.8, fs: 0.9, bs: 0.42, n: 1,
    roles: { m: "Male", f: "Female", b: "Joey", bs: "Joey" },
    info: {
      kinds: ["Northern koala", "Southern koala"],
      home: "Eucalyptus forests of eastern Australia.",
      food: "Only eucalyptus leaves.",
      life: "About 13–18 years.",
      babies: "Mother koala has 1 tiny joey. It lives in her pouch for 6 months, then rides on her back.",
      fact: "A koala is not a bear — it has a pouch like a kangaroo. It sleeps up to 20 hours a day.",
    },
  },
  {
    id: "wolf", emoji: "🐺",
    name: { en: "Wolf", mr: "लांडगा", hi: "भेड़िया" },
    models: { m: "wolf", f: "wolf", b: "wolf" }, h: 0.9, fs: 0.9, bs: 0.42, n: 5,
    roles: { m: "Male", f: "Female", b: "Pup", bs: "Pups" },
    info: {
      kinds: ["Indian wolf", "Himalayan wolf", "Grey wolf", "Arctic wolf", "Red wolf", "Ethiopian wolf"],
      home: "Grasslands, forests, mountains and snowy lands. The Indian wolf lives in the Deccan plateau.",
      food: "Deer, antelope, hares and other animals, hunted as a pack.",
      life: "About 6–13 years.",
      babies: "Mother wolf has 4 to 6 pups after about 2 months, in a den. The whole pack helps feed them.",
      fact: "Wolves howl to call their family together.",
    },
  },
  {
    id: "fox", emoji: "🦊",
    name: { en: "Fox", mr: "कोल्हा", hi: "लोमड़ी" },
    models: { m: "fox", f: "fox", b: "fox" }, h: 0.6, fs: 0.92, bs: 0.45, n: 4,
    roles: { m: "Dog fox", f: "Vixen", b: "Kit", bs: "Kits" },
    info: {
      kinds: ["Bengal fox", "Red fox", "Arctic fox", "Fennec fox"],
      home: "Grasslands, forests, deserts — and even cities.",
      food: "Mice, insects, birds, fruit and berries.",
      life: "About 3–10 years.",
      babies: "The vixen has 4 to 6 kits after about 7 weeks. They are born brown and fluffy with blue eyes.",
      fact: "A fox wraps its bushy tail around itself like a blanket to sleep.",
    },
  },
  {
    id: "rabbit", emoji: "🐰", photo: "pics/rabbit.webp",
    name: { en: "Rabbit", mr: "ससा", hi: "खरगोश" },
    models: { m: "rabbit", f: "rabbit", b: "rabbit" }, h: 0.6, fs: 0.95, bs: 0.45, n: 5, hop: true,
    roles: { m: "Buck", f: "Doe", b: "Kit", bs: "Kits" },
    info: {
      kinds: ["European rabbit (and all pet breeds)", "Cottontail rabbit", "Hares are their cousins"],
      home: "Meadows, woods and burrows under the ground.",
      food: "Grass, leafy plants and vegetables.",
      life: "About 8–12 years as a pet.",
      babies: "A doe has 4 to 8 kits after just one month. They are born with no fur and closed eyes.",
      fact: "A rabbit’s teeth never stop growing, so it keeps chewing to wear them down.",
    },
  },
  {
    id: "parrot", emoji: "🦜", photo: "pics/parrot.webp",
    name: { en: "Parrot", mr: "पोपट", hi: "तोता" },
    models: { m: "parrot", f: "parrot", b: "parrot" }, h: 0.8, fs: 0.95, bs: 0.45, n: 2, eggs: 3,
    roles: { m: "Male", f: "Female", b: "Chick", bs: "Chicks" },
    info: {
      kinds: ["Rose-ringed parakeet", "Alexandrine parakeet", "Scarlet macaw (this one!)", "African grey", "Cockatoo"],
      home: "Warm forests. India’s green parakeets live in trees, parks and gardens.",
      food: "Fruit, seeds, nuts and flowers.",
      life: "20–50 years — big macaws can live even longer.",
      babies: "Mother parrot lays 2 to 4 eggs in a tree hole. The chicks hatch after about 3–4 weeks with almost no feathers.",
      fact: "Many parrots can copy words and sounds they hear.",
    },
  },
  {
    id: "owl", emoji: "🦉", photo: "pics/owl.webp",
    name: { en: "Owl", mr: "घुबड", hi: "उल्लू" },
    models: { m: "owl", f: "owl", b: "owl" }, h: 0.7, fs: 1.05, bs: 0.5, n: 3, eggs: 5,
    roles: { m: "Male", f: "Female", b: "Owlet", bs: "Owlets" },
    info: {
      kinds: ["Barn owl (this one!)", "Spotted owlet", "Indian eagle-owl", "Snowy owl"],
      home: "Old buildings, tree holes and farms, all over the world.",
      food: "Mice and rats, caught at night.",
      life: "About 4 years in the wild, much longer in safe places.",
      babies: "Mother owl lays 4 to 7 eggs and keeps them warm for about a month. The owlets are white and fluffy.",
      fact: "An owl can turn its head almost all the way round, and flies without a sound.",
    },
  },
  {
    id: "hornbill", emoji: "🐦",
    name: { en: "Hornbill", mr: "धनेश", hi: "धनेश" },
    models: { m: "hornbill", f: "hornbill", b: "hornbill" }, h: 1.0, fs: 0.9, bs: 0.45, n: 1, eggs: 2,
    roles: { m: "Male", f: "Female", b: "Chick", bs: "Chick" },
    info: {
      kinds: ["Great hornbill", "Indian grey hornbill", "Malabar pied hornbill", "Ground hornbill (this one!)"],
      home: "Tall forests. The great hornbill lives in the Western Ghats and the north-east of India.",
      food: "Fruit — especially figs — and insects.",
      life: "About 35–50 years.",
      babies: "Mother lays 1 or 2 eggs. Many hornbills seal the mother inside a tree hole with mud, and the father feeds her through a little slit!",
      fact: "The great hornbill is the state bird of Kerala and Arunachal Pradesh.",
    },
  },
  {
    id: "turtle", emoji: "🐢",
    name: { en: "Turtle", mr: "कासव", hi: "कछुआ" },
    models: { m: "turtle", f: "turtle", b: "turtle" }, len: 0.9, fs: 1.1, bs: 0.3, n: 3, eggs: 14,
    roles: { m: "Male", f: "Female", b: "Hatchling", bs: "Hatchlings" },
    info: {
      kinds: ["Olive ridley sea turtle", "Green sea turtle", "Indian star tortoise", "Indian flapshell turtle"],
      home: "Seas, rivers, ponds and dry land (land turtles are called tortoises).",
      food: "Plants, jellyfish, fish and insects — depends on the kind.",
      life: "50–100 years or more.",
      babies: "An olive ridley mother digs a hole on the beach and lays about 100 eggs. At Velas beach in Maharashtra, people watch the babies race to the sea!",
      fact: "How warm the sand is decides whether the babies are boys or girls.",
    },
  },
  {
    id: "cobra", emoji: "🐍",
    name: { en: "Cobra", mr: "नाग", hi: "नाग" },
    models: { m: "cobra", f: "cobra", b: "cobra" }, len: 1.8, fs: 0.9, bs: 0.3, n: 3, eggs: 12,
    roles: { m: "Male", f: "Female", b: "Hatchling", bs: "Hatchlings" },
    info: {
      kinds: ["Indian (spectacled) cobra", "King cobra", "Monocled cobra"],
      home: "Fields, forests and near villages across India.",
      food: "Rats, frogs and other snakes.",
      life: "About 20 years.",
      babies: "The Indian cobra lays 10 to 30 eggs. The king cobra is the only snake that builds a nest of leaves for its eggs.",
      fact: "Cobras smell with their tongue. Always look from far — never touch a snake!",
    },
  },
  {
    id: "frog", emoji: "🐸",
    name: { en: "Frog", mr: "बेडूक", hi: "मेंढक" },
    models: { m: "frog", f: "frog", b: "tadpole" }, len: 0.55, fs: 1.15, bs: 0.35, n: 5, eggs: 30, hop: true,
    roles: { m: "Male", f: "Female", b: "Tadpole", bs: "Tadpoles" },
    info: {
      kinds: ["Indian bullfrog", "Common Indian toad", "Malabar gliding frog", "Purple frog"],
      home: "Ponds, puddles and wet forests — they come out when the monsoon starts.",
      food: "Insects, caught with a long sticky tongue.",
      life: "About 5–10 years.",
      babies: "Mother frog lays hundreds or even thousands of jelly eggs in water. They hatch into tadpoles, which grow legs and become frogs.",
      fact: "Frogs can drink water and breathe through their skin. Only the father croaks.",
    },
  },
  {
    id: "squirrel", emoji: "🐿️",
    name: { en: "Squirrel", mr: "खार", hi: "गिलहरी" },
    models: { m: "squirrel", f: "squirrel", b: "squirrel" }, h: 0.45, fs: 0.95, bs: 0.45, n: 3, hop: true,
    roles: { m: "Male", f: "Female", b: "Pup", bs: "Pups" },
    info: {
      kinds: ["Indian palm squirrel (three stripes)", "Indian giant squirrel (Shekru)", "Flying squirrel", "Grey squirrel"],
      home: "Trees, gardens and parks.",
      food: "Nuts, seeds, fruit and flowers.",
      life: "About 5 years.",
      babies: "Mother squirrel has 2 to 4 pups in a nest of grass and twigs, after about 6 weeks.",
      fact: "The Indian giant squirrel, the Shekru, is the state animal of Maharashtra.",
    },
  },
  {
    id: "duck", emoji: "🦆", photo: "pics/duck.webp",
    name: { en: "Duck", mr: "बदक", hi: "बत्तख" },
    models: { m: "duck", f: "duck", b: "duckling" }, h: 0.6, fs: 0.95, bs: 0.5, n: 4, eggs: 8,
    tint: { f: 0xe0bf95 },
    roles: { m: "Drake", f: "Duck", b: "Duckling", bs: "Ducklings" },
    info: {
      kinds: ["Mallard (this one!)", "Indian spot-billed duck", "Muscovy duck", "Pekin duck (white)"],
      home: "Ponds, lakes and rivers.",
      food: "Water plants, seeds, snails and insects.",
      life: "About 5–10 years.",
      babies: "Mother duck lays 8 to 13 eggs and sits on them for about 4 weeks. The ducklings can swim a few hours after hatching.",
      fact: "Ducklings follow the first thing they see — usually their mother — in a neat line.",
    },
  },
];

/* ============================================================
   Fish
     edible   true → "Fish we eat", false → "Fish we don’t eat"
     why      why we don't eat it (shown as a tag)
     eggs     eggs drawn in the family view (a handful stand for many)
     fs       mother size relative to father
   ============================================================ */
export const FISH = [
  {
    id: "tuna", emoji: "🐟", edible: true,
    name: { en: "Tuna", mr: "टुना", hi: "टूना" },
    model: "tuna", fs: 1.05, eggs: 40,
    info: {
      kinds: ["Skipjack tuna", "Yellowfin tuna", "Bluefin tuna", "Albacore"],
      home: "The open ocean, all over the world.",
      food: "Smaller fish, squid and shrimp.",
      life: "Up to about 40 years for bluefin.",
      eggs: "A big mother tuna can release millions of tiny floating eggs in one season.",
      fact: "Tuna never stop swimming — they need to move to breathe.",
    },
  },
  {
    id: "red-snapper", emoji: "🐟", edible: true,
    name: { en: "Red snapper", mr: "तांबोशी", hi: "लाल स्नैपर" },
    model: "red-snapper", fs: 1.05, eggs: 40,
    info: {
      kinds: ["Northern red snapper", "Mangrove red snapper", "Crimson snapper"],
      home: "Warm seas near rocks and coral reefs, including the Indian Ocean.",
      food: "Small fish, crabs and shrimp.",
      life: "It can live for more than 50 years.",
      eggs: "A big female can let go of hundreds of thousands of eggs at a time, and millions in a season.",
      fact: "The older and bigger the mother, the more eggs she lays.",
    },
  },
  {
    id: "grouper", emoji: "🐟", edible: true,
    name: { en: "Grouper", mr: "गोबरा", hi: "ग्रूपर" },
    model: "grouper", fs: 0.9, eggs: 40,
    info: {
      kinds: ["Coral grouper", "Orange-spotted grouper", "Giant grouper"],
      home: "Coral reefs and rocky seabeds in warm seas.",
      food: "Fish, crabs and octopus — swallowed whole!",
      life: "Some live 40 years or more.",
      eggs: "A mother grouper releases millions of tiny eggs that float in the sea.",
      fact: "Many groupers start life as girls and turn into boys when they grow big.",
    },
  },
  {
    id: "turbot", emoji: "🐟", edible: true,
    name: { en: "Turbot", mr: "टर्बोट", hi: "टर्बोट" },
    model: "turbot", fs: 1.1, eggs: 40,
    info: {
      kinds: ["Turbot", "Its flatfish cousins: flounder, halibut, sole"],
      home: "Sandy sea floors near Europe.",
      food: "Small fish, crabs and shellfish.",
      life: "About 25 years.",
      eggs: "A big female turbot can lay up to about 10 million eggs in a season.",
      fact: "A baby turbot swims upright, then one eye moves across its head and it lies flat on the sand.",
    },
  },
  {
    id: "swordfish", emoji: "🐟", edible: true,
    name: { en: "Swordfish", mr: "तलवार मासा", hi: "तलवार मछली" },
    model: "swordfish", fs: 1.2, eggs: 40,
    info: {
      kinds: ["There is just one kind of swordfish"],
      home: "Warm and cool parts of the open ocean.",
      food: "Squid and fish — it slashes them with its sword.",
      life: "About 10–15 years.",
      eggs: "A mother swordfish releases millions of eggs in a season.",
      fact: "Swordfish can warm up their eyes and brain to see better in cold, deep water.",
    },
  },
  {
    id: "catfish", emoji: "🐟", edible: true,
    name: { en: "Catfish", mr: "कॅटफिश", hi: "कैटफ़िश" },
    model: "catfish", fs: 1.05, eggs: 30,
    info: {
      kinds: ["Magur", "Singhi", "Pangasius (basa)", "Wallago", "Armoured catfish (this one!)"],
      home: "Rivers, lakes and ponds — very common in India.",
      food: "Almost anything on the bottom: insects, snails, plants and small fish.",
      life: "About 10–20 years.",
      eggs: "A mother catfish lays thousands of sticky eggs in a hidden nest, and often the father guards them.",
      fact: "Those ‘whiskers’ are called barbels — catfish use them to taste and feel in muddy water.",
    },
  },
  {
    id: "trout", emoji: "🐟", edible: true,
    name: { en: "Trout", mr: "ट्राउट", hi: "ट्राउट" },
    model: "trout", fs: 1.05, eggs: 30,
    info: {
      kinds: ["Rainbow trout", "Brown trout", "Brook trout"],
      home: "Cold, clean rivers and lakes — in India, in Kashmir, Himachal and the hills.",
      food: "Insects, worms and small fish.",
      life: "About 4–7 years.",
      eggs: "The mother digs a nest in river gravel with her tail and lays a few hundred to a few thousand eggs.",
      fact: "Trout need very clean, cold water — so finding trout means a river is healthy.",
    },
  },
  {
    id: "puffer", emoji: "🐡", edible: false, why: { en: "Poisonous!", mr: "विषारी!", hi: "ज़हरीली!" },
    name: { en: "Pufferfish", mr: "पफर मासा", hi: "पफर मछली" },
    model: "puffer", fs: 1.0, eggs: 24,
    info: {
      kinds: ["White-spotted puffer", "Porcupinefish", "Dogface puffer"],
      home: "Warm seas and coral reefs; a few live in rivers.",
      food: "Shellfish, crabs and coral, crunched with strong beak-like teeth.",
      life: "About 10 years.",
      eggs: "Mothers lay from a few hundred to a few thousand eggs, depending on the kind.",
      fact: "When scared, it gulps water and blows up like a spiky ball. Its body has a strong poison — never eat it.",
    },
  },
  {
    id: "clownfish", emoji: "🐠", edible: false, why: { en: "Reef pet", mr: "शोभेचा मासा", hi: "सजावटी मछली" },
    name: { en: "Clownfish", mr: "क्लाउनफिश", hi: "क्लाउनफ़िश" },
    model: "clownfish", fs: 1.3, eggs: 24,
    info: {
      kinds: ["Orange clownfish", "Tomato clownfish", "Pink skunk clownfish"],
      home: "Coral reefs, hiding inside stinging sea anemones that do not sting them.",
      food: "Tiny animals in the water and bits of algae.",
      life: "About 6–10 years.",
      eggs: "The mother lays 100 to 1,000 eggs on a rock. The father guards them and fans them with his fins until they hatch.",
      fact: "In a clownfish family, the mother is the biggest fish.",
    },
  },
  {
    id: "blue-tang", emoji: "🐠", edible: false, why: { en: "Reef fish", mr: "प्रवाळ मासा", hi: "मूंगा मछली" },
    name: { en: "Blue tang", mr: "ब्लू टँग", hi: "ब्लू टैंग" },
    model: "blue-tang", fs: 1.0, eggs: 30,
    info: {
      kinds: ["Blue tang (regal tang)", "Yellow tang", "Powder blue tang"],
      home: "Coral reefs of the Indian and Pacific Oceans.",
      food: "Algae (tiny sea plants).",
      life: "Up to about 20 years.",
      eggs: "Blue tangs release thousands of floating eggs in the open water, often at sunset.",
      fact: "It hides a sharp spine near its tail, like a tiny knife — that is why tangs are called surgeonfish.",
    },
  },
  {
    id: "goldfish", emoji: "🐠", edible: false, why: { en: "Pet fish", mr: "पाळीव मासा", hi: "पालतू मछली" },
    name: { en: "Goldfish", mr: "सोनेरी मासा", hi: "सुनहरी मछली" },
    model: "goldfish", fs: 1.05, eggs: 30,
    info: {
      kinds: ["Common goldfish", "Comet", "Oranda", "Fantail", "Bubble eye"],
      home: "Ponds and fish tanks. Wild cousins live in rivers.",
      food: "Fish flakes, water plants and insects.",
      life: "About 10–15 years with good care.",
      eggs: "A mother goldfish lays hundreds to a few thousand tiny eggs that stick to water plants.",
      fact: "Goldfish remember things for months — not just 3 seconds!",
    },
  },
  {
    id: "betta", emoji: "🐠", edible: false, why: { en: "Pet fish", mr: "पाळीव मासा", hi: "पालतू मछली" },
    name: { en: "Betta", mr: "बेट्टा मासा", hi: "बेट्टा मछली" },
    model: "betta", fs: 0.9, eggs: 24,
    info: {
      kinds: ["Siamese fighting fish", "Halfmoon betta", "Crowntail betta"],
      home: "Shallow rice paddies and ponds in South-East Asia, and home fish tanks.",
      food: "Insects and tiny worms.",
      life: "About 3–5 years.",
      eggs: "The father blows a nest of bubbles. The mother lays 30 to 500 eggs, and the father tucks each one into the bubbles and guards them.",
      fact: "Bettas can gulp air from the surface, so they live in water with little oxygen.",
    },
  },
  {
    id: "moorish-idol", emoji: "🐠", edible: false, why: { en: "Reef fish", mr: "प्रवाळ मासा", hi: "मूंगा मछली" },
    name: { en: "Moorish idol", mr: "मूरिश आयडॉल", hi: "मूरिश आइडल" },
    model: "moorish-idol", fs: 1.0, eggs: 24,
    info: {
      kinds: ["There is just one kind of Moorish idol"],
      home: "Coral reefs of the Indian and Pacific Oceans.",
      food: "Sponges and tiny animals on the reef.",
      life: "Not well known — scientists are still learning.",
      eggs: "They release lots of tiny eggs that float in the sea. Nobody has counted exactly how many!",
      fact: "Its long white fin trails behind it like a ribbon.",
    },
  },
  {
    id: "mandarin", emoji: "🐠", edible: false, why: { en: "Reef fish", mr: "प्रवाळ मासा", hi: "मूंगा मछली" },
    name: { en: "Mandarin fish", mr: "मँडरिन मासा", hi: "मैंडरिन मछली" },
    model: "mandarin", fs: 0.85, eggs: 18,
    info: {
      kinds: ["Mandarin dragonet", "Spotted mandarin"],
      home: "Coral reefs in the Pacific Ocean.",
      food: "Tiny shrimp-like animals.",
      life: "About 10–15 years.",
      eggs: "At sunset a mother and father rise up together, and she releases about 12 to 200 eggs.",
      fact: "Instead of scales it has smelly slime that tells hungry fish ‘yuck!’",
    },
  },
  {
    id: "butterfly-fish", emoji: "🐠", edible: false, why: { en: "Reef fish", mr: "प्रवाळ मासा", hi: "मूंगा मछली" },
    name: { en: "Butterfly fish", mr: "फुलपाखरू मासा", hi: "तितली मछली" },
    model: "butterfly-fish", fs: 1.0, eggs: 30,
    info: {
      kinds: ["Copperband butterflyfish", "Threadfin butterflyfish", "Raccoon butterflyfish"],
      home: "Coral reefs of warm seas, including around the Andaman and Lakshadweep islands.",
      food: "Coral polyps, worms and tiny animals.",
      life: "About 5–10 years.",
      eggs: "The pair releases thousands of floating eggs into the sea at night.",
      fact: "Many have a dark spot near the tail that looks like an eye, to trick hunters.",
    },
  },
  {
    id: "koi", emoji: "🐠", edible: false, why: { en: "Pond pet", mr: "पाळीव मासा", hi: "पालतू मछली" },
    name: { en: "Koi", mr: "कोई मासा", hi: "कोई मछली" },
    model: "koi", fs: 1.1, eggs: 30,
    info: {
      kinds: ["Kohaku (red & white)", "Showa", "Ogon (golden)", "Taisho Sanke"],
      home: "Garden ponds — they are colourful carp first bred in Japan.",
      food: "Plants, insects and fish pellets.",
      life: "About 25–35 years — some much longer.",
      eggs: "A big mother koi can lay hundreds of thousands of sticky eggs on pond plants.",
      fact: "Koi can learn to come when they are called at feeding time.",
    },
  },
];
